# Sign outgoing mail from no-reply@mail.booksome.top only.
Mode s
Syslog yes
SyslogSuccess yes
UserID opendkim:opendkim
Socket inet:8891@127.0.0.1
Canonicalization relaxed/relaxed
Domain mail.booksome.top
Selector booksome2026
KeyFile /etc/opendkim/keys/mail.booksome.top/booksome2026.private
InternalHosts /etc/opendkim/TrustedHosts
OversignHeaders From
